initial rename

diff --git a/rename-vmod-script b/rename-vmod-script
--- a/rename-vmod-script
+++ b/rename-vmod-script
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Script to rename libvmod-example into libvmod-foo.
+# Script to rename libvmod-cachehits into libvmod-foo.
 # (where "foo" is your new vmod name, of course.)
 #
 # Leaves the changes uncommitted in the working tree, so you get to fix any
@@ -13,28 +13,28 @@ set -o errexit
 NAME=$1
 if [ -z "$NAME" ]; then
 	echo "Usage: $0 <new-vmod-name-without-libvmod-prefix>"
-	echo "Rename libvmod-example source tree."
+	echo "Rename libvmod-cachehits source tree."
 	echo "If the name is an acronym, you can use capital letters."
 	echo
 	exit -1
 fi
 
-SYM_NAME=${NAME,,*}
-CAP_NAME=${NAME^?}
-UPP_NAME=${NAME^^?}
+SYM_NAME=cachehits
+CAP_NAME=CacheHits
+UPP_NAME=CACHEHITS
 
-if ! git diff-index --quiet HEAD --; then
-	echo "ERROR: Need a clean working tree. Run \"git stash\" first."
-	exit -2
-fi
+#if ! git diff-index --quiet HEAD --; then
+#	echo "ERROR: Need a clean working tree. Run \"git stash\" first."
+#	exit -2
+#fi
 
-git mv src/vmod_example.c src/vmod_${SYM_NAME}.c
-git mv src/vmod_example.vcc src/vmod_${SYM_NAME}.vcc
+git mv src/vmod_cachehits.c src/vmod_${SYM_NAME}.c
+git mv src/vmod_cachehits.vcc src/vmod_${SYM_NAME}.vcc
 
-git grep -z -l example | xargs -0 sed -i -s -e "s/example/${SYM_NAME}/g"
-git grep -z -l Example | xargs -0 sed -i -s -e "s/Example/${CAP_NAME}/g"
-git grep -z -l EXAMPLE | xargs -0 sed -i -s -e "s/EXAMPLE/${UPP_NAME}/g"
-sed -i '/circleci.com\/gh\/varnishcache\/libvmod-example/d' README.rst
+git grep -z -l cachehits | xargs -0 sed -i -s -e "s/cachehits/${SYM_NAME}/g"
+git grep -z -l CacheHits | xargs -0 sed -i -s -e "s/CacheHits/${CAP_NAME}/g"
+git grep -z -l CACHEHITS | xargs -0 sed -i -s -e "s/CACHEHITS/${UPP_NAME}/g"
+sed -i '/circleci.com\/gh\/varnishcache\/libvmod-cachehits/d' README.rst
 
 git rm -f rename-vmod-script
 
@@ -45,5 +45,5 @@ cat <<EOF
 All done.
 
 For your cut&paste needs:
-git commit -a -m "Automatic rename of libvmod-example to libvmod-${SYM_NAME}."
+git commit -a -m "Automatic rename of libvmod-cachehits to libvmod-${SYM_NAME}."
 EOF
